---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
  labels:
    app: backend
stringData:
  DB_PASSWORD: admin
  JWT_SECRET: devopsexampleSuperSecretKey

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
  labels:
    app: backend
data:
  DB_HOST: localhost
  DB_USER: root
  DB_NAME: crud_apps
  RESET_ADMIN_PASS: "true"

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend-container
          image: rajatrulaniya/devsecops-backend:latest
          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
                  

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: RESET_ADMIN_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RESET_ADMIN_PASS

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000